/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Factions that are part of the game.
 */
export type Faction =
  | (
      | 'Galactic Empire'
      | 'Galactic Republic'
      | 'Separatist Alliance'
      | 'Rebel Alliance'
    )
  | string;

/**
 * An army list.
 */
export interface Roster {
  name: string;
  faction: Faction;
  format: ('Skirmish' | 'Standard') | Format;
  units: [RosterUnit, ...RosterUnit[]];
}
/**
 * An army list (game) format.
 */
export interface Format {
  name: string;
  points: number;
  ranks: {
    [k: string]: [number, number];
  };
}
export interface RosterUnit {
  /**
   * Name and sub-title, if any, of the selected unit.
   */
  name: string;
  /**
   * Upgrades attached to the unit.
   */
  upgrades?: string[];
  /**
   * Upgrades attached to the unit.
   */
  loadout?: string[];
}
