/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Upgrades attached to the unit.
 */
export type UpgradeSet = [string, ...string[]];

export interface RosterUnit {
  /**
   * Name and sub-title, if any, of the selected unit.
   */
  name: string;
  upgrades?: UpgradeSet;
  loadout?: UpgradeSet;
}
